export const arr=[
  {
    "title": "Mechanical Engineer",
    "description": "Job Description\n\nMontgomery College has an immediate need for a full-time\nMechanical Engineer...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Rockville, MD",
    "salary": 91652,
    "category": "Engineering",
    "job_id": "d6AgbqspkOLVO-vKAAAAAA==",
    "apply_link": "https://jobs.chronicle.com/job/37859419/mechanical-engineer/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Meets with users to determine mechanical requirements\n• Designs HVAC, electrical, plumbing systems\n• Prepares engineering drawings\n• Submits for permits\n• Collaborates with Procurement Department\n• Inspects construction\n• Project manage and oversee outside contractor\n• Provide construction administrative services\n• Serve as mechanical engineering subject matter expert\n• Provides technical advice\n• Reviews engineering drawings\n• Inspects engineering systems\n• Develop capital replacement plans\n• Investigates and resolves engineering problems",
    "qualifications": "• Bachelor's degree in mechanical engineering\n• Four or more years of experience\n• Knowledge of mechanical and plumbing engineering principles\n• Knowledge of energy conservation and codes\n• Working knowledge of architecture and electrical systems\n• Ability to perform professional engineering work\n• Ability to communicate effectively\n• Ability to establish working relationships\n• Ability to work on multiple projects\n• Strong organizational skills\n• Valid driver’s License\n• State of Maryland Professional Engineering (PE) license",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdjPldVvWbUjsDEkILaEDKta98wUBYI7SOxH5P&s=0"
  },
  {
    "title": "ICAM Engineer",
    "description": "ICAM Engineer\n\nRemote - but must work East Coast hours\n\nDo you thrive in building secure and scalable solutions?...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "East Riverdale, MD",
    "salary": 185000,
    "category": "Engineering",
    "job_id": "f023t5SXU6kUJXYuAAAAAA==",
    "apply_link": "https://www.glassdoor.com/job-listing/icam-engineer-grant-leading-technology-llc-JV_KO0,13_KE14,42.htm?jl=1009341132725&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Write processes, issue logs, and root cause analysis\n• Responsible for development and implementation of SSO solutions\n• Administer systems like Ping Federate and PingAccess\n• Gather user input and develop technical requirements\n• Work closely with clients during deployments\n• Ensure product integration with various systems\n• Create technical materials\n• Integrate access management tools\n• Facilitate workflow customization\n• Install, upgrade and configure identity management applications",
    "qualifications": "• Bachelor’s degree\n• 3-6 years of ICAM solutions experience\n• Extensive work with Ping Federate and PingAccess\n• Experience with Federation (SAML/WSFed)\n• Experience with IDP and SP connections\n• Knowledge of SAML 2.0, OAuth 2.0, OpenID Connect\n• Experience with Active Directory and LDAP\n• Experience with SQL databases\n• Knowledge of compliance standards (NIST, GDPR, HIPAA)\n• Ability to work in team-oriented environment\n• Experience creating design documents\n• U.S. citizenship",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgAxv8uJU7_GUVapMwkttV-OEuR84n-iTjWHgy&s=0"
  },
  {
    "title": "Platform Engineer",
    "description": "This is a U.S. based position. All of the programs we support require U.S. citizenship to be eligible for employment...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Arlington, VA",
    "salary": 175000,
    "category": "Engineering",
    "job_id": "SD5kfGgPl9IiP6r2AAAAAA==",
    "apply_link": "https://www.ziprecruiter.com/c/Raft-Company-Website/Job/Platform-Engineer/-in-Arlington,VA?jid=52c8b19e04b0a867&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Implement and manage system automation using Ansible/Puppet\n• Deploy/maintain Kubernetes clusters (RKE2/Rancher)\n• Manage open-source applications (NiFi, Kafka, etc.)\n• Ensure system performance and security\n• Collaborate with teams for technical solutions\n• Maintain documentation",
    "qualifications": "• Bachelor's degree in Computer Science/IT/Engineering\n• Experience with Ansible, Puppet, Kubernetes\n• RHEL and Windows system management\n• Strong problem-solving skills\n• Excellent communication abilities\n• Active Top Secret clearance with SCI eligibility",
    "logo": null
  },
  {
    "title": "DevOps Software Engineer",
    "description": "Job Description\n\nDevOps Software Engineer\n\nDevOps is an agile development practice and mindset that uses agile principles...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Annapolis Junction, MD",
    "salary": 197500,
    "category": "Engineering",
    "job_id": "aWyeKXHcfaOrdBr7AAAAAA==",
    "apply_link": "https://jobs.baesystems.com/global/en/job/114877BR/DevOps-Software-Engineer?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Manage tools for development/deployment\n• Integrate project functions across product lifecycle\n• Identify automatable processes\n• Select/deploy CI/CD tools\n• Implement development/testing tools\n• Ensure system security\n• Build CI/CD pipelines\n• Collaborate across teams",
    "qualifications": "• Solid understanding of DevOps\n• 5+ years experience managing dev/deployment tools\n• 5+ years CI/CD experience\n• System Administration experience (Windows/Linux)\n• Programming experience (Java, Groovy, Python)\n• IDE experience (Eclipse, VS Code)\n• Source control experience\n• Virtualized environment experience\n• Container platform experience",
    "logo": null
  },
  {
    "title": "Full Performance System Engineer",
    "description": "Kavaliro is seeking a Full Performance System Engineer to support a client in Virginia...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "McLean, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "gQV-MIxGdI3sh1VEAAAAAA==",
    "apply_link": "https://jobs.kavaliro.com/Full-Performance-System-Engineer-Jobs-in-McLean-VA/12358038?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "Provide technical support and system engineering",
    "qualifications": "• Experience with server technologies (MVS, Linux, UNIX, Windows)\n• Enterprise IT experience\n• C2E server management\n• Multi-system environment experience\n• Network requirements understanding\n• Organizational standards knowledge\n• Problem solving skills\n• Analytical planning skills\n• Project management techniques\n• Communication skills\n• Independent/team work ability\n• Requirements tracking experience\n• Technology research skills\n• TS/SCI clearance with Full Scope Polygraph",
    "logo": null
  },
  {
    "title": "Electrical Design Eng-HOH 25-3",
    "description": "Description\n\nThis is a program for Active-Duty Military Members through Hiring our Heroes (HoH) Corporate Fellowship...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Arlington, VA",
    "salary": 135950,
    "category": "Engineering",
    "job_id": "NQDIu1fHQCX9X8WjAAAAAA==",
    "apply_link": "https://www.linkedin.com/jobs/view/electrical-design-eng-hoh-25-3-at-amazon-web-services-aws-4236431082?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Conduct technical planning\n• Deploy/maintain Kubernetes clusters\n• Manage open-source applications\n• Ensure system performance\n• Collaborate with teams\n• Maintain documentation\n• Travel to sites",
    "qualifications": "• Experience with electrical system design\n• Critical equipment knowledge\n• Data center equipment understanding\n• Constructability knowledge\n• Bachelor's degree in Electrical Engineering\n• 1+ year industrial/commercial electrical design\n• Design documentation experience",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDhrsiwqZ87o_GbEtiPnJBd_9_wDeh86Wk6uMM&s=0"
  },
  {
    "title": "Industrial Automation Engineer",
    "description": "Industrial Automation Engineer\n\nKey Role:\n\nLead the design, implementation, and maintenance of automation and control systems...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "McLean, VA",
    "salary": 126800,
    "category": "Engineering",
    "job_id": "My_o7rDM0TI_MjX8AAAAAA==",
    "apply_link": "https://www.indeed.com/viewjob?jk=03fae870c715b915&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Lead automation system design/implementation\n• Leverage Rockwell Automation platforms\n• Work with multidisciplinary teams\n• Mentor junior team members\n• Provide technical leadership",
    "qualifications": "• 4+ years with Rockwell/Allen-Bradley/Siemens\n• AutoCAD Electrical experience\n• P&ID diagram creation\n• Independent/team work ability\n• Secret clearance\n• Bachelor's degree in IT/Engineering/Automation",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA6_xjmivev1fdSnDkygDVA7J2Ajz2DDD6Gwj-&s=0"
  },
  {
    "title": "Service Engineer",
    "description": "An employer is looking for a qualified Service Engineer in the Reston, VA or Redmond, WA area...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Arlington, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "F2pgv4vgT94FMsoNAAAAAA==",
    "apply_link": "https://insightglobal.com/jobs/find_a_job/virginia/arlington/service-engineer/job-399813/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Respond/resolve urgent service problems\n• Recommend automation solutions\n• Analyze problems using data tools\n• Apply data classification policies",
    "qualifications": "Active Top Secret SCI with Full Scope Polygraph",
    "logo": null
  },
  {
    "title": "System Engineer",
    "description": "Description\n\nWe are seeking a detail-oriented and technically skilled System Engineer to join our team...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Falls Church, VA",
    "salary": 119538,
    "category": "Engineering",
    "job_id": "X7Qp5SLJyCkLd_g6AAAAAA==",
    "apply_link": "https://www.ziprecruiter.com/c/Leidos/Job/System-Engineer/-in-Falls-Church,VA?jid=03e1d8a3391d00e8&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Technical planning and system design\n• System integration and validation\n• Evaluate alternatives for system optimization\n• Requirements analysis\n• Trade studies and interface definition\n• Project technical management\n• Support system testing\n• Cross-functional collaboration",
    "qualifications": "• TS/SCI w/ Poly Clearance\n• Bachelor’s degree in Systems Engineering/CS/EE\n• 4-8 years experience\n• System design/integration experience\n• Requirements analysis proficiency\n• System testing experience\n• Problem-solving skills\n• Systems integration knowledge\n• Communication skills\n• Leadership ability",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNKz0vyYWBzdQTzSlCli_sPy8vUYCJLF_y78H-&s=0"
  },
  {
    "title": "Structural Engineer – Wood Framing Design Specialist",
    "description": "We are currently looking for a Structural Engineer with specialized experience in the design and document preparation...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Washington, DC",
    "salary": 0,
    "category": "Engineering",
    "job_id": "Wy-HpA98Ai1afBMmAAAAAA==",
    "apply_link": "https://www.indeed.com/viewjob?jk=2d24240942ca3d92&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "Grow into management of wood-frame design",
    "qualifications": "• 5+ years residential design experience\n• Project management ability\n• Leadership and mentoring skills",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjYNd-FvnkyQK3cldNDCeMAhVpceMszez_wuUD&s=0"
  },
  {
    "title": "Embedded Software Engineer, Intelligence Systems, Mid-Level",
    "description": "Verified Job On Employer Career Site\n\nJob Summary:\n\nAnduril Industries is a defense technology company focused on transforming military capabilities...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Reston, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "ziJR43Ebv_cZcrO6AAAAAA==",
    "apply_link": "https://www.linkedin.com/jobs/view/embedded-software-engineer-intelligence-systems-mid-level-at-jobright-ai-4277110000?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Develop/integrate software for robotic systems\n• Own software solutions end-to-end\n• Write code to build products\n• Collaborate across teams\n• Bridge technical/non-technical teams",
    "qualifications": "• Embedded systems experience (robotics/electronics)\n• Networking experience\n• Hardware testing/automation\n• Constrained environment development\n• Low-level embedded software skills\n• Complex system navigation\n• Certification implementation\n• C/C++/Rust/Go proficiency\n• Linux/containerization knowledge\n• U.S. Top Secret clearance",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc11c46XEF7nUag98qauGWM3tBuQH8ELcz8Cbg&s=0"
  },
  {
    "title": "FreeFlyer Space Systems Engineer",
    "description": "a.i. solutions is seeking an articulate engineer passionate about space to join our FreeFlyer support team...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Lanham, MD",
    "salary": 92500,
    "category": "Engineering",
    "job_id": "hB_VKB_NznOBTqCyAAAAAA==",
    "apply_link": "https://spacecrew.com/space-jobs/m67k9mf8-ai-solutions-freeflyer-space-systems-engineer?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Provide FreeFlyer technical support\n• Build demonstrations/presentations\n• Support customer site visits\n• Conduct instructional courses\n• Collaborate with aerospace engineers\n• Review design documents\n• Support licensing/registration\n• Identify improvement areas",
    "qualifications": "• Bachelor’s degree in Aerospace Engineering/Physics/CS\n• U.S. citizenship\n• Technical writing experience\n• Orbital mechanics knowledge\n• Flight dynamics tool experience\n• Programming skills (C#/Java/Python)\n• Customer communication ability",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqHYBYMsMNhIfWtK5kYROh-jGWO4uOC6uA1EGx&s=0"
  },
  {
    "title": "Project Engineer",
    "description": "Req ID: 6295\nTravel: Up to 25%\nNumber of Openings: 1\n\nAchieve more in your career with the nation’s leading specialty concrete contractor...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Arlington, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "NsxN6Xltja1An8XoAAAAAA==",
    "apply_link": "https://www.indeed.com/viewjob?jk=908b315febaf5530&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Generate/approve monthly billing\n• Develop/manage project schedules\n• Analyze job cost summaries\n• Generate/approve budgets\n• Collaborate with pre-construction\n• Generate RFPs\n• Manage financial reporting\n• Approve invoices\n• Generate technical records\n• Coordinate as-built records\n• Manage project turnover\n• Lead LEAN/SQP committee\n• Ensure subcontractor compliance",
    "qualifications": "• Bachelor’s degree + 2 years experience OR 6 years construction experience\n• Microsoft Office proficiency\n• Document interpretation skills\n• Mathematical proficiency\n• Cost accounting understanding\n• Construction software knowledge\n• Contract/specification understanding\n• Problem-solving ability",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIgwZwTciw5FaZGkdWVhtEriHYse2xxrSIT7Ef&s=0"
  },
  {
    "title": "Director of Engineering",
    "description": "Who We Want\n\nAre you excited about shaping the future of intelligent, no-code technology?...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Falls Church, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "m4-7YPSWBaC4ZoVyAAAAAA==",
    "apply_link": "https://www.linkedin.com/jobs/view/director-of-engineering-at-blink-tech-inc-4277804216?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Define/execute engineering initiatives\n• Integrate AI/LLMs into products\n• Research emerging technologies\n• Lead/grow engineering teams\n• Foster innovation culture\n• Architect scalable systems\n• Guide no-code architecture\n• Collaborate with product/design teams\n• Implement engineering best practices\n• Ensure platform reliability",
    "qualifications": "• Bachelor's in Computer Science/Engineering\n• 8+ years software engineering\n• 3+ years technical leadership\n• AI/ML integration experience\n• API development skills\n• AWS environment experience\n• JavaScript/Java/Oracle proficiency\n• NodeJS/Angular CLI expertise\n• Secure coding knowledge\n• Problem-solving skills\n• Communication abilities",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNuLmWtI1dcty-ZUUhCTN2qoIiIK3EGWesJNVS&s=0"
  },
  {
    "title": "F5 Network Engineer",
    "description": "A client of Insight Global is looking for 1 F5 Network Engineers to work fully onsite at the Pentagon in Arlington, VA...",
    "job_type": "on site",
    "employment_type": "fulltime",
    "location": "Arlington, VA",
    "salary": 0,
    "category": "Engineering",
    "job_id": "6xwgtb2XVsyb6INsAAAAAA==",
    "apply_link": "https://insightglobal.com/jobs/find_a_job/virginia/arlington/f5-network-engineer/job-399986/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    "responsibilities": "• Design/plan/build networks\n• Configure routers/switches/firewalls\n• Coordinate LAN/WAN improvements\n• Monitor networks\n• Maintain network integrity",
    "qualifications": "Active Top Secret SCI with Full Scope Polygraph",
    "logo": null
  }
]