//@ts-nocheck
"use client"
import { Theme } from "@radix-ui/themes";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createContext, useContext, useState } from "react";
export const MainContext = createContext();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [email, setEmail] = useState("a@gmail.com");
  const [pass, setPass] = useState("1234");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Theme>
        <MainContext.Provider value={{ email, setEmail, pass, setPass }}>
          {children}
        </MainContext.Provider>
        </Theme>

      </body>
    </html>
  );
}




export function useMaincontext() {
  const data = useContext(MainContext);
  return data;
}
